import { jsPDF } from 'jspdf';
import { InvestigationData } from '@/lib/store';

export default class PDFGenerator {
  generate(investigationData: InvestigationData): void {
    const doc = new jsPDF();
    const { extracted, result } = investigationData;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;

    const addText = (
      text: string,
      x: number = 20,
      size: number = 12,
      weight: 'normal' | 'bold' = 'normal'
    ) => {
      doc.setFontSize(size);
      doc.setFont('helvetica', weight === 'bold' ? 'bold' : 'normal');
      doc.text(text, x, yPosition);
      yPosition += size / 2 + 3;
    };

    const addLine = () => {
      doc.setDrawColor(200, 200, 200);
      doc.line(20, yPosition, pageWidth - 20, yPosition);
      yPosition += 8;
    };

    // Header
    doc.setFillColor(99, 102, 241); // Primary color
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.text('JobShield AI', 20, 25);

    doc.setTextColor(0, 0, 0);
    yPosition = 50;

    // Title
    addText('Job Offer Investigation Report', 20, 18, 'bold');
    addText(`Analysis Date: ${new Date().toLocaleDateString()}`, 20, 10);
    addLine();

    // Trust Score Summary
    addText('Executive Summary', 20, 14, 'bold');
    yPosition += 2;
    addText(`Trust Score: ${result.trustScore}%`, 20, 12);
    addText(`Risk Level: ${result.riskLevel.toUpperCase()}`, 20, 12);
    yPosition += 4;
    
    // Summary text with word wrapping
    const summaryLines = doc.splitTextToSize(result.summary, pageWidth - 40);
    doc.setFontSize(11);
    summaryLines.forEach((line: string) => {
      doc.text(line, 20, yPosition);
      yPosition += 6;
    });
    yPosition += 4;
    addLine();

    // Extracted Information
    addText('Extracted Information', 20, 14, 'bold');
    yPosition += 3;

    const infoItems = [
      ['Company:', extracted.company || 'Not found'],
      ['Recruiter:', extracted.recruiter || 'Not found'],
      ['Email:', extracted.recruiterEmail || 'Not found'],
      ['Phone:', extracted.phoneNumber || 'Not found'],
      ['Website:', extracted.website || 'Not found'],
      ['Salary:', extracted.salary || 'Not found'],
      ['Job Role:', extracted.jobRole || 'Not found'],
      ['Joining Date:', extracted.joiningDate || 'Not found'],
    ];

    doc.setFontSize(11);
    infoItems.forEach(([label, value]) => {
      doc.setFont('helvetica', 'bold');
      doc.text(label, 25, yPosition);
      doc.setFont('helvetica', 'normal');
      doc.text(value, 70, yPosition);
      yPosition += 7;
    });

    yPosition += 4;
    addLine();

    // Suspicious Indicators
    if (result.suspiciousIndicators.length > 0) {
      addText('Suspicious Indicators Found', 20, 14, 'bold');
      yPosition += 3;

      doc.setFontSize(11);
      result.suspiciousIndicators.forEach((indicator) => {
        doc.text(`• ${indicator}`, 25, yPosition);
        yPosition += 6;
      });

      yPosition += 4;
      addLine();
    }

    // Detailed Analysis
    addText('Detailed Analysis', 20, 14, 'bold');
    yPosition += 3;

    const analyses = [
      ['Email Domain Analysis', result.emailDomainAnalysis],
      ['Company Analysis', result.companyAnalysis],
      ['Recruiter Analysis', result.recruiterAnalysis],
      ['Website Analysis', result.websiteAnalysis],
      ['Phone Analysis', result.phoneAnalysis],
    ];

    doc.setFontSize(11);
    analyses.forEach(([title, content]) => {
      if (yPosition > pageHeight - 40) {
        doc.addPage();
        yPosition = 20;
      }

      doc.setFont('helvetica', 'bold');
      doc.text(title, 20, yPosition);
      yPosition += 6;

      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(content, pageWidth - 40);
      lines.forEach((line: string) => {
        if (yPosition > pageHeight - 40) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(line, 25, yPosition);
        yPosition += 5;
      });

      yPosition += 6;
    });

    // Recommendations
    if (yPosition > pageHeight - 80) {
      doc.addPage();
      yPosition = 20;
    }

    addLine();
    addText('Recommendations', 20, 14, 'bold');
    yPosition += 3;

    doc.setFontSize(11);
    result.recommendations.forEach((rec) => {
      if (yPosition > pageHeight - 40) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(`✓ ${rec}`, 25, yPosition);
      yPosition += 6;
    });

    // Footer
    const now = new Date();
    const timestamp = `${now.toLocaleDateString()} ${now.toLocaleTimeString()}`;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by JobShield AI on ${timestamp}`,
      20,
      pageHeight - 10
    );

    // Download
    doc.save(`JobShield-Investigation-${new Date().toISOString().split('T')[0]}.pdf`);
  }
}
